NAME 		= libft.a
FLAGS 		= -Wall -Werror -Wextra
SRC 		= ft_isalpha.c\
		ft_isalnum.c\
		ft_isascii.c\
		ft_isdigit.c\
		ft_isprint.c\
		ft_memset.c\
		ft_strlen.c\
		ft_tolower.c\
		ft_toupper.c\
		ft_strncmp.c\
		ft_bzero.c\
		ft_memcpy.c\
		ft_memmove.c\
		ft_strlcpy.c\
		ft_strlcat.c\
		ft_strchr.c\
		ft_strrchr.c\
		ft_memchr.c\
		ft_memcmp.c\
		ft_strnstr.c\
		ft_atoi.c\
		ft_calloc.c\
		ft_strdup.c\
		ft_printdec.c\
		ft_strjoin.c\
		ft_strtrim.c\
		ft_itoa.c\
		ft_putchar_fd.c\
		ft_strmapi.c\
		ft_striteri.c\
		ft_putstr_fd.c\
		ft_putendl_fd.c\
		ft_putnbr_fd.c\
		ft_split.c\
		ft_printchar.c\
		ft_printf.c\
		ft_printhexa.c\
		ft_printptr.c\
		ft_printstr.c\
		ft_printunsigned.c\
		get_next_line.c\
		get_next_line_utils.c

OBJECTS = $(SRC:.c=.o)

.c.o:
		gcc $(FLAGS) -c $< -o $(<:.c=.o)

$(NAME) : $(OBJECTS)
		ar rcs $(NAME) $(OBJECTS)

all : $(NAME)

clean:
		rm -f $(OBJECTS)

fclean:	clean
		rm -f $(NAME) $(OBJECTS)

re: fclean all

.PHONY : all re fclean clean
